spring:
  application:
    name: podcast-generator
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    url: jdbc:postgresql://localhost:5432/podcast_db
    username: podcastadmin
    password: K8MJGwIJ9Vgek7$Mncu*
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    ignore-missing-migrations: true
    ignore-missing-repeatable-migrations: true
    validateOnMigrate: false
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      model: gpt-4
      temperature: 0.7
  security:
    oauth2:
      client:
        registration:
          zitadel:
            client-id: ${ZITADEL_CLIENT_ID}
            client-secret: ${ZITADEL_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
              - urn:zitadel:iam:org:project:roles
        provider:
          zitadel:
            issuer-uri: https://${ZITADEL_DOMAIN}
            user-name-attribute: preferred_username

elevenlabs:
  api:
    key: ${ELEVENLABS_API_KEY}
    voice-settings:
      stability: 0.5
      similarity-boost: 0.75
    model-id: eleven_multilingual_v2

server:
  port: 8080
  servlet:
    context-path: /

zitadel:
  org-id: ${ZITADEL_ORG_ID}
  domain: ${ZITADEL_DOMAIN}

app:
  uploads:
    base-path: uploads
    voice-previews-path: ${app.uploads.base-path}/voice-previews
    podcasts-path: ${app.uploads.base-path}/podcasts

logging:
  level:
    ai.bluefields.podcastgen: DEBUG
    ai.bluefields.podcastgen.controller: DEBUG
    ai.bluefields.podcastgen.model: DEBUG
    org.springframework: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot.autoconfigure: DEBUG
    org.hibernate: WARN
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
