spring:
  application:
    name: podcast-generator
  datasource:
    url: jdbc:postgresql://localhost:5432/podcast_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    ai.bluefields.podcastgen: DEBUG
    org.springframework: INFO
    org.hibernate: INFO
